<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class InsertDemoData extends CI_Controller {
    
    public function index() {
        // Only run in development environment
        if (ENVIRONMENT !== 'development') {
            show_error('This script can only run in development environment', 403);
        }
        
        $this->load->model('Customer_data_model');
        
        // Demo data array (first 5 shown, expand to 50)
        // $demo_customers = [
        //     [
        //         'first_name' => 'John',
        //         'last_name' => 'Smith',
        //         'email' => 'john.smith@example.com',
        //         'phone' => '5551234567',
        //         'age' => 35,
        //         'membership_from' => '2024-01-15',
        //         'membership_to' => '2025-01-15',
        //         'country_id' => 1,
        //         'access_level' => 'admin',
        //         'account_status' => 'Active',
        //         'gender' => 'Male',
        //         'product_interest' => 'Product A,Service C'
        //     ],
        //     // Add more entries...
        // ];

        $demo_customers = [
    [
        'first_name' => 'John',
        'last_name' => 'Smith',
        'email' => 'john.smith@example.com',
        'phone' => '5551234567',
        'age' => 35,
        'membership_from' => '2024-01-15',
        'membership_to' => '2025-01-15',
        'country_id' => 1,
        'access_level' => 'admin',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product A,Service C'
    ],
    [
        'first_name' => 'Sarah',
        'last_name' => 'Johnson',
        'email' => 'sarah.j@example.com',
        'phone' => '5559876543',
        'age' => 42,
        'membership_from' => '2024-02-01',
        'membership_to' => '2025-02-01',
        'country_id' => 2,
        'access_level' => 'admin',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Product B'
    ],
    [
        'first_name' => 'Michael',
        'last_name' => 'Williams',
        'email' => 'michael.w@example.com',
        'phone' => '5554567890',
        'age' => 28,
        'membership_from' => '2024-03-10',
        'membership_to' => '2025-03-10',
        'country_id' => 1,
        'access_level' => 'admin',
        'account_status' => 'Inactive',
        'gender' => 'Male',
        'product_interest' => 'Product A,Product B,Service C'
    ],
    [
        'first_name' => 'Emily',
        'last_name' => 'Brown',
        'email' => 'emily.b@example.com',
        'phone' => '5557891234',
        'age' => 31,
        'membership_from' => '2024-01-20',
        'membership_to' => '2025-01-20',
        'country_id' => 3,
        'access_level' => 'employee',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Service C'
    ],
    [
        'first_name' => 'David',
        'last_name' => 'Jones',
        'email' => 'david.j@example.com',
        'phone' => '5552345678',
        'age' => 45,
        'membership_from' => '2024-02-15',
        'membership_to' => '2025-02-15',
        'country_id' => 2,
        'access_level' => 'sales',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product A'
    ],
    [
        'first_name' => 'Jennifer',
        'last_name' => 'Davis',
        'email' => 'jennifer.d@example.com',
        'phone' => '5558765432',
        'age' => 29,
        'membership_from' => '2024-03-01',
        'membership_to' => '2025-03-01',
        'country_id' => 1,
        'access_level' => 'employee',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Product A,Product B'
    ],
    [
        'first_name' => 'Robert',
        'last_name' => 'Miller',
        'email' => 'robert.m@example.com',
        'phone' => '5553456789',
        'age' => 38,
        'membership_from' => '2024-01-25',
        'membership_to' => '2025-01-25',
        'country_id' => 3,
        'access_level' => 'employee',
        'account_status' => 'Inactive',
        'gender' => 'Male',
        'product_interest' => 'Product B'
    ],
    [
        'first_name' => 'Jessica',
        'last_name' => 'Wilson',
        'email' => 'jessica.w@example.com',
        'phone' => '5556543210',
        'age' => 26,
        'membership_from' => '2024-02-10',
        'membership_to' => '2025-02-10',
        'country_id' => 2,
        'access_level' => 'sales',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Service C'
    ],
    [
        'first_name' => 'Thomas',
        'last_name' => 'Moore',
        'email' => 'thomas.m@example.com',
        'phone' => '5557654321',
        'age' => 33,
        'membership_from' => '2024-03-05',
        'membership_to' => '2025-03-05',
        'country_id' => 1,
        'access_level' => 'admin',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product A,Service C'
    ],
    [
        'first_name' => 'Amanda',
        'last_name' => 'Taylor',
        'email' => 'amanda.t@example.com',
        'phone' => '5555432109',
        'age' => 40,
        'membership_from' => '2024-01-30',
        'membership_to' => '2025-01-30',
        'country_id' => 3,
        'access_level' => 'sales',
        'account_status' => 'Inactive',
        'gender' => 'Female',
        'product_interest' => 'Product B,Service C'
    ],
    [
        'first_name' => 'Christopher',
        'last_name' => 'Anderson',
        'email' => 'chris.a@example.com',
        'phone' => '5554321098',
        'age' => 27,
        'membership_from' => '2024-02-20',
        'membership_to' => '2025-02-20',
        'country_id' => 1,
        'access_level' => 'sales',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product A,Product B,Service C'
    ],
    [
        'first_name' => 'Melissa',
        'last_name' => 'Thomas',
        'email' => 'melissa.t@example.com',
        'phone' => '5553210987',
        'age' => 32,
        'membership_from' => '2024-03-15',
        'membership_to' => '2025-03-15',
        'country_id' => 2,
        'access_level' => 'employee',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Product A'
    ],
    [
        'first_name' => 'Daniel',
        'last_name' => 'Jackson',
        'email' => 'daniel.j@example.com',
        'phone' => '5552109876',
        'age' => 36,
        'membership_from' => '2024-01-05',
        'membership_to' => '2025-01-05',
        'country_id' => 3,
        'access_level' => 'sales',
        'account_status' => 'Inactive',
        'gender' => 'Male',
        'product_interest' => 'Product B'
    ],
    [
        'first_name' => 'Michelle',
        'last_name' => 'White',
        'email' => 'michelle.w@example.com',
        'phone' => '5551098765',
        'age' => 30,
        'membership_from' => '2024-02-25',
        'membership_to' => '2025-02-25',
        'country_id' => 1,
        'access_level' => 'admin',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Service C'
    ],
    [
        'first_name' => 'Matthew',
        'last_name' => 'Harris',
        'email' => 'matthew.h@example.com',
        'phone' => '5550987654',
        'age' => 25,
        'membership_from' => '2024-03-20',
        'membership_to' => '2025-03-20',
        'country_id' => 2,
        'access_level' => 'employee',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product A,Product B'
    ],
    [
        'first_name' => 'Ashley',
        'last_name' => 'Martin',
        'email' => 'ashley.m@example.com',
        'phone' => '5559876123',
        'age' => 29,
        'membership_from' => '2024-01-10',
        'membership_to' => '2025-01-10',
        'country_id' => 3,
        'access_level' => 'admin',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Product B,Service C'
    ],
    [
        'first_name' => 'Joshua',
        'last_name' => 'Thompson',
        'email' => 'joshua.t@example.com',
        'phone' => '5558765123',
        'age' => 34,
        'membership_from' => '2024-02-05',
        'membership_to' => '2025-02-05',
        'country_id' => 1,
        'access_level' => 'employee',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product A'
    ],
    [
        'first_name' => 'Stephanie',
        'last_name' => 'Garcia',
        'email' => 'stephanie.g@example.com',
        'phone' => '5557654123',
        'age' => 41,
        'membership_from' => '2024-03-25',
        'membership_to' => '2025-03-25',
        'country_id' => 2,
        'access_level' => 'sales',
        'account_status' => 'Inactive',
        'gender' => 'Female',
        'product_interest' => 'Product A,Service C'
    ],
    [
        'first_name' => 'Kevin',
        'last_name' => 'Martinez',
        'email' => 'kevin.m@example.com',
        'phone' => '5556543123',
        'age' => 28,
        'membership_from' => '2024-01-15',
        'membership_to' => '2025-01-15',
        'country_id' => 3,
        'access_level' => 'admin',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product B'
    ],
    [
        'first_name' => 'Laura',
        'last_name' => 'Robinson',
        'email' => 'laura.r@example.com',
        'phone' => '5555432123',
        'age' => 37,
        'membership_from' => '2024-02-28',
        'membership_to' => '2025-02-28',
        'country_id' => 1,
        'access_level' => 'employee',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Product A,Product B,Service C'
    ],
    [
        'first_name' => 'James',
        'last_name' => 'Clark',
        'email' => 'james.c@example.com',
        'phone' => '5554321123',
        'age' => 44,
        'membership_from' => '2024-03-08',
        'membership_to' => '2025-03-08',
        'country_id' => 2,
        'access_level' => 'sales',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Service C'
    ],
    [
        'first_name' => 'Elizabeth',
        'last_name' => 'Rodriguez',
        'email' => 'elizabeth.r@example.com',
        'phone' => '5553211123',
        'age' => 31,
        'membership_from' => '2024-01-22',
        'membership_to' => '2025-01-22',
        'country_id' => 3,
        'access_level' => 'admin',
        'account_status' => 'Inactive',
        'gender' => 'Female',
        'product_interest' => 'Product A,Product B'
    ],
    [
        'first_name' => 'Ryan',
        'last_name' => 'Lewis',
        'email' => 'ryan.l@example.com',
        'phone' => '5552101123',
        'age' => 26,
        'membership_from' => '2024-02-12',
        'membership_to' => '2025-02-12',
        'country_id' => 1,
        'access_level' => 'employee',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product B'
    ],
    [
        'first_name' => 'Megan',
        'last_name' => 'Lee',
        'email' => 'megan.l@example.com',
        'phone' => '5551091123',
        'age' => 33,
        'membership_from' => '2024-03-18',
        'membership_to' => '2025-03-18',
        'country_id' => 2,
        'access_level' => 'sales',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Product A,Service C'
    ],
    [
        'first_name' => 'Nicholas',
        'last_name' => 'Walker',
        'email' => 'nicholas.w@example.com',
        'phone' => '5550981123',
        'age' => 39,
        'membership_from' => '2024-01-08',
        'membership_to' => '2025-01-08',
        'country_id' => 3,
        'access_level' => 'admin',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product A,Product B,Service C'
    ],
    [
        'first_name' => 'Samantha',
        'last_name' => 'Hall',
        'email' => 'samantha.h@example.com',
        'phone' => '5551234561',
        'age' => 30,
        'membership_from' => '2024-02-14',
        'membership_to' => '2025-02-14',
        'country_id' => 1,
        'access_level' => 'employee',
        'account_status' => 'Inactive',
        'gender' => 'Female',
        'product_interest' => 'Product B'
    ],
    [
        'first_name' => 'Andrew',
        'last_name' => 'Allen',
        'email' => 'andrew.a@example.com',
        'phone' => '5554561237',
        'age' => 35,
        'membership_from' => '2024-03-22',
        'membership_to' => '2025-03-22',
        'country_id' => 2,
        'access_level' => 'sales',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product A'
    ],
    [
        'first_name' => 'Olivia',
        'last_name' => 'Young',
        'email' => 'olivia.y@example.com',
        'phone' => '5557894563',
        'age' => 28,
        'membership_from' => '2024-01-18',
        'membership_to' => '2025-01-18',
        'country_id' => 3,
        'access_level' => 'admin',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Service C'
    ],
    [
        'first_name' => 'Jacob',
        'last_name' => 'King',
        'email' => 'jacob.k@example.com',
        'phone' => '5559871237',
        'age' => 42,
        'membership_from' => '2024-02-08',
        'membership_to' => '2025-02-08',
        'country_id' => 1,
        'access_level' => 'employee',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product A,Product B'
    ],
    [
        'first_name' => 'Sophia',
        'last_name' => 'Wright',
        'email' => 'sophia.w@example.com',
        'phone' => '5556547893',
        'age' => 31,
        'membership_from' => '2024-03-12',
        'membership_to' => '2025-03-12',
        'country_id' => 2,
        'access_level' => 'sales',
        'account_status' => 'Inactive',
        'gender' => 'Female',
        'product_interest' => 'Product A,Service C'
    ],
    [
        'first_name' => 'William',
        'last_name' => 'Scott',
        'email' => 'william.s@example.com',
        'phone' => '5553216549',
        'age' => 47,
        'membership_from' => '2024-01-28',
        'membership_to' => '2025-01-28',
        'country_id' => 3,
        'access_level' => 'admin',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product B,Service C'
    ],
    [
        'first_name' => 'Isabella',
        'last_name' => 'Green',
        'email' => 'isabella.g@example.com',
        'phone' => '5551472583',
        'age' => 25,
        'membership_from' => '2024-02-18',
        'membership_to' => '2025-02-18',
        'country_id' => 1,
        'access_level' => 'employee',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Product A'
    ],
    [
        'first_name' => 'Ethan',
        'last_name' => 'Adams',
        'email' => 'ethan.a@example.com',
        'phone' => '5552583691',
        'age' => 36,
        'membership_from' => '2024-03-28',
        'membership_to' => '2025-03-28',
        'country_id' => 2,
        'access_level' => 'sales',
        'account_status' => 'Inactive',
        'gender' => 'Male',
        'product_interest' => 'Product B'
    ],
    [
        'first_name' => 'Mia',
        'last_name' => 'Baker',
        'email' => 'mia.b@example.com',
        'phone' => '5553692581',
        'age' => 32,
        'membership_from' => '2024-01-12',
        'membership_to' => '2025-01-12',
        'country_id' => 3,
        'access_level' => 'admin',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Service C'
    ],
    [
        'first_name' => 'Alexander',
        'last_name' => 'Nelson',
        'email' => 'alexander.n@example.com',
        'phone' => '5557418529',
        'age' => 39,
        'membership_from' => '2024-02-22',
        'membership_to' => '2025-02-22',
        'country_id' => 1,
        'access_level' => 'employee',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product A,Product B,Service C'
    ],
    [
        'first_name' => 'Charlotte',
        'last_name' => 'Carter',
        'email' => 'charlotte.c@example.com',
        'phone' => '5558529637',
        'age' => 29,
        'membership_from' => '2024-03-02',
        'membership_to' => '2025-03-02',
        'country_id' => 2,
        'access_level' => 'sales',
        'account_status' => 'Inactive',
        'gender' => 'Female',
        'product_interest' => 'Product A'
    ],
    [
        'first_name' => 'Benjamin',
        'last_name' => 'Mitchell',
        'email' => 'benjamin.m@example.com',
        'phone' => '5559638527',
        'age' => 44,
        'membership_from' => '2024-01-07',
        'membership_to' => '2025-01-07',
        'country_id' => 3,
        'access_level' => 'admin',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product B,Service C'
    ],
    [
        'first_name' => 'Abigail',
        'last_name' => 'Perez',
        'email' => 'abigail.p@example.com',
        'phone' => '5551593572',
        'age' => 27,
        'membership_from' => '2024-02-17',
        'membership_to' => '2025-02-17',
        'country_id' => 1,
        'access_level' => 'employee',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Product A,Service C'
    ],
    [
        'first_name' => 'Daniel',
        'last_name' => 'Roberts',
        'email' => 'daniel.r@example.com',
        'phone' => '5553571592',
        'age' => 38,
        'membership_from' => '2024-03-27',
        'membership_to' => '2025-03-27',
        'country_id' => 2,
        'access_level' => 'sales',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product B'
    ],
    [
        'first_name' => 'Harper',
        'last_name' => 'Turner',
        'email' => 'harper.t@example.com',
        'phone' => '5557531592',
        'age' => 33,
        'membership_from' => '2024-01-14',
        'membership_to' => '2025-01-14',
        'country_id' => 3,
        'access_level' => 'admin',
        'account_status' => 'Inactive',
        'gender' => 'Female',
        'product_interest' => 'Product A,Product B'
    ],
    [
        'first_name' => 'Jackson',
        'last_name' => 'Phillips',
        'email' => 'jackson.p@example.com',
        'phone' => '5559513572',
        'age' => 41,
        'membership_from' => '2024-02-24',
        'membership_to' => '2025-02-24',
        'country_id' => 1,
        'access_level' => 'employee',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Service C'
    ],
    [
        'first_name' => 'Evelyn',
        'last_name' => 'Campbell',
        'email' => 'evelyn.c@example.com',
        'phone' => '5553579512',
        'age' => 26,
        'membership_from' => '2024-03-14',
        'membership_to' => '2025-03-14',
        'country_id' => 2,
        'access_level' => 'sales',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Product A,Product B,Service C'
    ],
    [
        'first_name' => 'Sebastian',
        'last_name' => 'Parker',
        'email' => 'sebastian.p@example.com',
        'phone' => '5551597532',
        'age' => 45,
        'membership_from' => '2024-01-24',
        'membership_to' => '2025-01-24',
        'country_id' => 3,
        'access_level' => 'admin',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product A'
    ],
    [
        'first_name' => 'Avery',
        'last_name' => 'Evans',
        'email' => 'avery.e@example.com',
        'phone' => '5557539512',
        'age' => 31,
        'membership_from' => '2024-02-04',
        'membership_to' => '2025-02-04',
        'country_id' => 1,
        'access_level' => 'employee',
        'account_status' => 'Inactive',
        'gender' => 'Female',
        'product_interest' => 'Product B,Service C'
    ],
    [
        'first_name' => 'Jack',
        'last_name' => 'Edwards',
        'email' => 'jack.e@example.com',
        'phone' => '5559517532',
        'age' => 37,
        'membership_from' => '2024-03-24',
        'membership_to' => '2025-03-24',
        'country_id' => 2,
        'access_level' => 'sales',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product A,Service C'
    ],
    [
        'first_name' => 'Scarlett',
        'last_name' => 'Collins',
        'email' => 'scarlett.c@example.com',
        'phone' => '5553571598',
        'age' => 29,
        'membership_from' => '2024-01-04',
        'membership_to' => '2025-01-04',
        'country_id' => 3,
        'access_level' => 'admin',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Product B'
    ],
    [
        'first_name' => 'Owen',
        'last_name' => 'Stewart',
        'email' => 'owen.s@example.com',
        'phone' => '5551593578',
        'age' => 34,
        'membership_from' => '2024-02-14',
        'membership_to' => '2025-02-14',
        'country_id' => 1,
        'access_level' => 'employee',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product A,Product B'
    ],
    [
        'first_name' => 'Grace',
        'last_name' => 'Sanchez',
        'email' => 'grace.s@example.com',
        'phone' => '5557531598',
        'age' => 40,
        'membership_from' => '2024-03-04',
        'membership_to' => '2025-03-04',
        'country_id' => 2,
        'access_level' => 'sales',
        'account_status' => 'Inactive',
        'gender' => 'Female',
        'product_interest' => 'Service C'
    ],
    [
        'first_name' => 'Luke',
        'last_name' => 'Morris',
        'email' => 'luke.m@example.com',
        'phone' => '5559513578',
        'age' => 28,
        'membership_from' => '2024-01-29',
        'membership_to' => '2025-01-29',
        'country_id' => 3,
        'access_level' => 'admin',
        'account_status' => 'Active',
        'gender' => 'Male',
        'product_interest' => 'Product A,Product B,Service C'
    ],
    [
        'first_name' => 'Chloe',
        'last_name' => 'Rogers',
        'email' => 'chloe.r@example.com',
        'phone' => '5553579518',
        'age' => 32,
        'membership_from' => '2024-02-19',
        'membership_to' => '2025-02-19',
        'country_id' => 1,
        'access_level' => 'employee',
        'account_status' => 'Active',
        'gender' => 'Female',
        'product_interest' => 'Product A'
    ]
];
        
        $inserted = 0;
        $errors = [];
        
        foreach ($demo_customers as $customer) {
            if ($this->Customer_data_model->insert_customer($customer)) {
                $inserted++;
            } else {
                $errors[] = $customer['email'];
            }
        }
        
        echo "Inserted: $inserted customers<br>";
        if (!empty($errors)) {
            echo "Failed to insert: " . implode(', ', $errors);
        }
    }
}